import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  worldConfig: {},
  terrainConfig: {}
};

export const dataSlice = createSlice({
  name: 'data',
  initialState,
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    // builder
    //   .addCase(incrementAsync.pending, (state) => {
    //     state.status = 'loading';
    //   })
    //   .addCase(incrementAsync.fulfilled, (state, action) => {
    //     state.status = 'idle';
    //     state.value += action.payload;
    //   });
  },
});

export const { } = dataSlice.actions;

export default dataSlice.reducer;
